export {default as Configuration } from './Configuration';
export{default as CustomTextField} from './CustomTextField';
import Header from './Header';
import Footer from './Footer';
import About from './About';
import Home from './Home';
import MicroServices from './MicroServices';
import Dashboard from './Dashboard';
import SignUp from './SignUp';
export { Header, Footer, About, Home, MicroServices, Dashboard, SignUp };