name: Frontend Build and Deploy

on:
  push:
    branches:
      - feature/push-commit-check

env:
  REGISTRY: docker.io
  OWNER: ${{secrets.DOCKER_USERNAME}}
  IMAGE_NAME: k8s-designer-backend
  TAG: $(cat VERSION.txt)-$(echo ${{github.sha}} | cut -c1-7)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
      - name: Lint code
        run: |
          npm run linting
      - name: Run tests
        run: |
          npm run test
      - name: Create build
        run: |
          npm run build
      - name: Build Docker image
        run: |
          docker build -t ${{env.OWNER}}/${{env.IMAGE_NAME}}:${{env.TAG}} .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{env.OWNER}}/${{env.IMAGE_NAME}}:${{env.TAG}}